"""Updating Users table ( Adding is_varified Column)  - Second Migartion

Revision ID: 09cdeb9b861a
Revises: 1676385a7c97
Create Date: 2026-10-08 10:45:18.846880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cdeb9b861a'
down_revision: Union[str, Sequence[str], None] = '1676385a7c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verfied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verfied')
    # ### end Alembic commands ###
