"""Updating Users table ( Adding is_verified  Column)  - Third Migartion

Revision ID: 7616e50f0555
Revises: 09cdeb9b861a
Create Date: 2026-10-08 13:18:07.105853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7616e50f0555'
down_revision: Union[str, Sequence[str], None] = '09cdeb9b861a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_verfied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verfied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
