"""Updating Refresh Tokenss table ( Adding revoked  Column)  - Fourth Migartion

Revision ID: 822f30710392
Revises: 7616e50f0555
Create Date: 2026-10-08 21:44:08.907508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822f30710392'
down_revision: Union[str, Sequence[str], None] = '7616e50f0555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###
